# save it in the same directory. this script is to analyze the csv generated by the other scripts 
#!/usr/bin/env python3
import os
import glob
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def main():
    # 1. Ask for the directory containing the CSVs once
    target_dir = input("Enter the directory path containing the CSV files: ").strip()
    if not os.path.isdir(target_dir):
        print(f"Error: Directory not found: {target_dir}")
        return

    # 2. Find all stress files to identify the unique test prefixes
    stress_files = glob.glob(os.path.join(target_dir, "*_stress.csv"))
    
    if not stress_files:
        print("No files ending in '_stress.csv' found in this directory.")
        return

    print(f"Found {len(stress_files)} test pair(s). Processing...")

    for stress_path in stress_files:
        # Determine the prefix and logger path
        file_dir = os.path.dirname(stress_path)
        base_filename = os.path.basename(stress_path)
        prefix = base_filename.replace('_stress.csv', '')
        logger_path = os.path.join(file_dir, f"{prefix}_logger.csv")

        # Skip if the corresponding logger doesn't exist
        if not os.path.exists(logger_path):
            print(f"Skipping '{prefix}': Matching logger file not found.")
            continue

        print(f"-> Analyzing: {prefix}")

        # --- 3. LOAD & CLEAN DATA ---
        # Stress Data: Ignore the first frame (index 0)
        df_s = pd.read_csv(stress_path).iloc[1:].reset_index(drop=True)
        
        # Logger Data
        df_l = pd.read_csv(logger_path)

        # --- 4. CALCULATIONS ---
        # Latency & Jitter
        df_s['Latency_ms'] = df_s['Latency_Sec'] * 1000
        df_s['Jitter_ms'] = df_s['Latency_ms'].diff().abs().fillna(0)
        
        p95 = np.percentile(df_s['Latency_ms'], 95)
        p99 = np.percentile(df_s['Latency_ms'], 99)
        avg_lat = df_s['Latency_ms'].mean()
        avg_jit = df_s['Jitter_ms'].mean()

        # Class IDs (parsing space-separated IDs)
        class_ids_list = df_s['Class_IDs'].astype(str).fillna("")
        all_class_ids = []
        for entry in class_ids_list:
            all_class_ids.extend([int(c) for c in entry.split() if c.isdigit()])
        unique_cls, counts_cls = np.unique(all_class_ids, return_counts=True)

        # --- 5. PLOTTING ---
        fig, axes = plt.subplots(4, 1, figsize=(14, 18))

        # Plot 1: Latency (Stress)
        axes[0].plot(df_s['Frame_Index'], df_s['Latency_ms'], label='Latency', color='#1f77b4', alpha=0.8)
        axes[0].axhline(p95, color='orange', linestyle='--', label=f'p95: {p95:.2f}ms')
        axes[0].axhline(p99, color='red', linestyle='--', label=f'p99: {p99:.2f}ms')
        axes[0].set_title(f'[{prefix}] Frame Latency & Tail Metrics')
        axes[0].set_ylabel('ms')
        axes[0].grid(True, linestyle='--', alpha=0.5)
        axes[0].legend()

        # Plot 2: Jitter (Stress)
        axes[1].plot(df_s['Frame_Index'], df_s['Jitter_ms'], label='Jitter', color='#d62728', alpha=0.8)
        axes[1].set_title(f'[{prefix}] Frame-to-Frame Jitter')
        axes[1].set_ylabel('ms')
        axes[1].grid(True, linestyle='--', alpha=0.5)

        # Plot 3: Power & GPU (Logger) - Combined on one plot with dual axes
        ax3_twin = axes[2].twinx()
        p1, = axes[2].plot(df_l['Time_s'], df_l['Power_W'], color='green', label='Power (W)')
        p2, = ax3_twin.plot(df_l['Time_s'], df_l['GPU_Usage_percent'], color='purple', label='GPU %', alpha=0.4)
        axes[2].set_title(f'[{prefix}] Power & GPU Utilization')
        axes[2].set_ylabel('Power (Watts)')
        ax3_twin.set_ylabel('GPU Usage (%)')
        axes[2].legend(handles=[p1, p2])
        axes[2].grid(True, linestyle='--', alpha=0.3)

        # Plot 4: Class Frequencies
        axes[3].bar(unique_cls.astype(str), counts_cls, color='teal')
        axes[3].set_title(f'[{prefix}] Object Detection Distribution')
        axes[3].set_xlabel('Class ID')
        axes[3].set_ylabel('Frequency')

        plt.tight_layout()
        plot_path = os.path.join(file_dir, f"{prefix}_analysis.png")
        plt.savefig(plot_path)
        plt.close()

        # --- 6. SAVE NUMERIC RESULTS (TXT) ---
        results_txt = os.path.join(file_dir, f"{prefix}_results.txt")
        with open(results_txt, 'w') as f:
            f.write(f"--- RESULTS FOR PREFIX: {prefix} ---\n")
            f.write(f"Source Stress: {os.path.basename(stress_path)}\n")
            f.write(f"Source Logger: {os.path.basename(logger_path)}\n")
            f.write("-" * 40 + "\n")
            f.write(f"Total Frames Analyzed: {len(df_s)} (Row 0 skipped)\n")
            f.write(f"Avg Latency:           {avg_lat:.2f} ms\n")
            f.write(f"p95 Latency:           {p95:.2f} ms\n")
            f.write(f"p99 Latency:           {p99:.2f} ms\n")
            f.write(f"Avg Jitter:            {avg_jit:.2f} ms\n")
            f.write(f"Detections:            min={df_s['Detection_Count'].min()}, max={df_s['Detection_Count'].max()}\n")
            f.write("\nClass ID Frequencies:\n")
            for uid, cnt in zip(unique_cls, counts_cls):
                f.write(f"  Class {uid}: {cnt}\n")
            f.write("-" * 40 + "\n")
            f.write(f"Avg Power Usage:       {df_l['Power_W'].mean():.2f} W\n")
            f.write(f"Avg GPU Usage:         {df_l['GPU_Usage_percent'].mean():.1f}%\n")
            f.write(f"Peak RAM Usage:        {df_l['RAM_MB'].max():.1f} MB\n")
            f.write(f"Max CPU Temp:          {df_l['CPU_Temp_C'].max():.1f} °C\n")

        print(f"   Done. Saved files to directory: {file_dir}")

if __name__ == "__main__":
    main()
